config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    Product.create(product_params)
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Litknit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Lit Knit', root_path, class: 'navbar-brand' %>
      <%= link_to 'Add A Submission', new_product_path, class: 'nav-link' %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>From roving to lace</h1>
<h3>A place to share your stash, projects and more!</h3>

<%= @products.each do |product| %>
  <div class="booyah-box col-10 offset-1">
    <%= product.name %><br />
    <%= product.description %>
  </div>
  <hr />
<% end %>

app/views/products/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>What do you want to share?</h1>
  <%= simple_form_for @product do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.submit 'Submit' %>
  <% end %>
</div>